import type { DesignTemplate } from "@/types";

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: "instagram-post",
    name: "인스타그램 포스트",
    category: "소셜미디어",
    width: 1080,
    height: 1080,
    thumbnail: "/templates/instagram-post.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1080,
        props: { fill: "#ffffff" },
      },
      {
        id: "main-image",
        type: "image",
        x: 40,
        y: 40,
        width: 1000,
        height: 700,
        props: { placeholder: true, borderRadius: 16 },
      },
      {
        id: "title",
        type: "text",
        x: 40,
        y: 780,
        width: 1000,
        height: 80,
        props: {
          text: "제목을 입력하세요",
          fontSize: 48,
          fontWeight: "bold",
          fill: "#1a1a1a",
        },
      },
      {
        id: "subtitle",
        type: "text",
        x: 40,
        y: 880,
        width: 1000,
        height: 60,
        props: {
          text: "설명을 입력하세요",
          fontSize: 24,
          fill: "#666666",
        },
      },
    ],
  },
  {
    id: "instagram-story",
    name: "인스타그램 스토리",
    category: "소셜미디어",
    width: 1080,
    height: 1920,
    thumbnail: "/templates/instagram-story.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        props: { fill: "#000000" },
      },
      {
        id: "main-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1080,
        height: 1920,
        props: { placeholder: true, objectFit: "cover" },
      },
      {
        id: "overlay-text",
        type: "text",
        x: 80,
        y: 1500,
        width: 920,
        height: 120,
        props: {
          text: "스토리 텍스트",
          fontSize: 56,
          fontWeight: "bold",
          fill: "#ffffff",
          textAlign: "center",
        },
      },
    ],
  },
  {
    id: "facebook-ad",
    name: "페이스북 광고",
    category: "광고",
    width: 1200,
    height: 628,
    thumbnail: "/templates/facebook-ad.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 1200,
        height: 628,
        props: { fill: "#f0f2f5" },
      },
      {
        id: "main-image",
        type: "image",
        x: 0,
        y: 0,
        width: 600,
        height: 628,
        props: { placeholder: true },
      },
      {
        id: "headline",
        type: "text",
        x: 640,
        y: 180,
        width: 520,
        height: 80,
        props: {
          text: "광고 헤드라인",
          fontSize: 42,
          fontWeight: "bold",
          fill: "#1a1a1a",
        },
      },
      {
        id: "description",
        type: "text",
        x: 640,
        y: 280,
        width: 520,
        height: 120,
        props: {
          text: "광고 설명을 입력하세요. 제품의 장점을 강조해보세요.",
          fontSize: 22,
          fill: "#666666",
          lineHeight: 1.5,
        },
      },
      {
        id: "cta-button",
        type: "shape",
        x: 640,
        y: 440,
        width: 240,
        height: 56,
        props: {
          shapeType: "rect",
          fill: "#1877f2",
          borderRadius: 8,
          text: "자세히 보기",
          textFill: "#ffffff",
          fontSize: 20,
        },
      },
    ],
  },
  {
    id: "youtube-thumbnail",
    name: "유튜브 썸네일",
    category: "소셜미디어",
    width: 1280,
    height: 720,
    thumbnail: "/templates/youtube-thumbnail.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        props: { fill: "#000000" },
      },
      {
        id: "main-image",
        type: "image",
        x: 0,
        y: 0,
        width: 1280,
        height: 720,
        props: { placeholder: true, objectFit: "cover" },
      },
      {
        id: "title",
        type: "text",
        x: 60,
        y: 500,
        width: 800,
        height: 120,
        props: {
          text: "영상 제목",
          fontSize: 72,
          fontWeight: "bold",
          fill: "#ffffff",
          stroke: "#000000",
          strokeWidth: 3,
        },
      },
    ],
  },
  {
    id: "banner-wide",
    name: "와이드 배너",
    category: "광고",
    width: 1920,
    height: 480,
    thumbnail: "/templates/banner-wide.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 1920,
        height: 480,
        props: {
          fill: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        },
      },
      {
        id: "product-image",
        type: "image",
        x: 1340,
        y: 20,
        width: 540,
        height: 440,
        props: { placeholder: true },
      },
      {
        id: "headline",
        type: "text",
        x: 80,
        y: 120,
        width: 1200,
        height: 80,
        props: {
          text: "프로모션 헤드라인",
          fontSize: 56,
          fontWeight: "bold",
          fill: "#ffffff",
        },
      },
      {
        id: "subtext",
        type: "text",
        x: 80,
        y: 220,
        width: 1200,
        height: 60,
        props: {
          text: "지금 바로 확인하세요",
          fontSize: 28,
          fill: "#e0e0ff",
        },
      },
      {
        id: "cta",
        type: "shape",
        x: 80,
        y: 320,
        width: 220,
        height: 56,
        props: {
          shapeType: "rect",
          fill: "#ffffff",
          borderRadius: 28,
          text: "바로가기",
          textFill: "#667eea",
          fontSize: 20,
          fontWeight: "bold",
        },
      },
    ],
  },
  {
    id: "poster-a4",
    name: "A4 포스터",
    category: "인쇄물",
    width: 2480,
    height: 3508,
    thumbnail: "/templates/poster-a4.svg",
    elements: [
      {
        id: "bg",
        type: "background",
        x: 0,
        y: 0,
        width: 2480,
        height: 3508,
        props: { fill: "#ffffff" },
      },
      {
        id: "hero-image",
        type: "image",
        x: 120,
        y: 120,
        width: 2240,
        height: 1600,
        props: { placeholder: true, borderRadius: 24 },
      },
      {
        id: "title",
        type: "text",
        x: 120,
        y: 1840,
        width: 2240,
        height: 160,
        props: {
          text: "이벤트 제목",
          fontSize: 96,
          fontWeight: "bold",
          fill: "#1a1a1a",
          textAlign: "center",
        },
      },
      {
        id: "details",
        type: "text",
        x: 240,
        y: 2100,
        width: 2000,
        height: 400,
        props: {
          text: "이벤트 상세 내용을 입력하세요.\n일시: 2024년 00월 00일\n장소: 서울시 강남구",
          fontSize: 40,
          fill: "#444444",
          lineHeight: 1.8,
          textAlign: "center",
        },
      },
    ],
  },
];

export function getTemplatesByCategory(category?: string): DesignTemplate[] {
  if (!category) return DESIGN_TEMPLATES;
  return DESIGN_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(id: string): DesignTemplate | undefined {
  return DESIGN_TEMPLATES.find((t) => t.id === id);
}

export function getCategories(): string[] {
  return [...new Set(DESIGN_TEMPLATES.map((t) => t.category))];
}
